rbac:
  enabled: false

podLabels:
  createdfor: addinn


service:
  internalPort: 80
  externalPort: 8080

ingress:
  enabled: true
  issuer: letsencrypt-issuer
  externaldns: enabled
  className: nginx
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"

# env:
#   - name: APIURL
#     value: 'https://backend-gah-freightsure.dev3.addinn-group.com/'
#   - name: URL
#     value: 'https://front-portal-freightsure.dev3.addinn-group.com/'
#   - name: API_URL_KONNECT_POST
#     value: 'https://api.preprod.konnect.network/api/v2/payments/init-payment'
#   - name: API_URL_KONNECT_GET
#     value: 'https://api.preprod.konnect.network/api/v2/payments/'
#   - name: RECEIVERWALLETID
#     value: '648835de5918ffe19497b65d'


livenessProbe: {}
readinessProbe: {}
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi
nodeSelector: {}
metrics:
  enabled: true
  port: 80



dockerSecret:
  config: '{"auths":{"reg.addinn-group.com": {"auth": "YWRtaW46ZHN3NEF1RUdLVQ=="},"https://index.docker.io/v1/":{"auth":"dzZkaW86NzcxNGYzNjMtMzhiNS00MGM0LWJmNTktZmQzZjVlNTllMjE3"}}}'
